# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_advisor_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='advisor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
        migrations.AddField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Advisor'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
