# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20160505_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='photo',
            field=models.ImageField(upload_to='/media/faces'),
        ),
    ]
