# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20160508_0226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='uid',
            new_name='student',
        ),
    ]
