# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(choices=[('P', 'Professor'), ('AP', 'Associate Professor'), ('I', 'Instructor'), ('NA', 'Not Available')], max_length=100)),
                ('age', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.SmallIntegerField()),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='students',
            field=models.CommaSeparatedIntegerField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='advisor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Advisor'),
            preserve_default=False,
        ),
    ]
