# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20160501_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='photo',
            field=models.ImageField(upload_to='/static/faces/'),
        ),
    ]
